name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Install dependencies
        run: npm i

      - name: Install daisyUI
        run: npm i -D daisyui@latest

      - name: Install TailwindCSS
        run: npx tailwindcss -i ./input.css -o ./public/tailwind.css

      - name: Verify TailwindCSS output
        run: ls -l ./public/tailwind.css

      - name: Build Dioxus project
        run: npm run build

      - name: Verify build output
        run: ls -al ./dist

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1  # ใช้ action สำหรับอัปโหลด artifact ที่เหมาะสม
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-pages-artifact@v1  # ใช้ action สำหรับดาวน์โหลด artifact ที่เหมาะสม
        with:
          name: github-pages

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'